spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false
  application:
    name: lre-gateway
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8080

feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000